<?php

namespace Drupal\formd8\Form;

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form\FormBase;
//use Drupal\file\Entity\File;


class FormSubscribe extends FormBase
{
  public function getFormId()
  {
    return 'subscribe_form';
  }

  public function buildForm(array $form, FormStateInterface $form_state)
  {

    $form['first_name'] = [
      '#type' => 'textfield',
      '#title' => $this->t('first name'),
      '#required' => true,
      '#size' => 60,
      '#default_value' => ' ',
      '#maxlength' => 128,
      '#wrapper_attributes' => ['class' => 'col-md-6 col-xs-12']
    ];
    $form['last_name'] = [
      '#type' => 'textfield',
      '#title' => $this->t('last name'),
      '#required' => true,
      '#size' => 60,
      '#default_value' => ' ',
      '#wrapper_attributes' => ['class' => 'col-md-6 col-xs-12']
    ];
    $form['email'] = [
      '#type' => 'email',
      '#title' => $this->t('email'),
      '#required' => true,
      '#default_value' => ' ',
      '#wrapper_attributes' => ['class' => 'col-md-6 col-xs-12']
    ];
    $form['picture'] = array(
      '#title' => t('picture'),
      '#description' => $this->t('Chossir Image gif png jpg jpeg'),
      '#type' => 'managed_file',
      '#upload_location' => 'public://images/',
      '#upload_validators' => array(
        'file_validate_extensions' => array('gif png jpg jpeg')),
    );
    $form['phone'] = [
      '#type' => 'tel',
      '#title' => $this->t('phone'),
      '#required' => true,
      '#default_value' => ' ',
      '#wrapper_attributes' => ['class' => 'col-md-6 col-xs-12']
    ];
    $form['select'] = [
      '#type' => 'select',
      '#title' => $this
        ->t('Select element'),
      '#options' => [
        '1' => $this
          ->t('One'),
        '2' => [
          '2.1' => $this
            ->t('Two point one'),
          '2.2' => $this
            ->t('Two point two'),
        ],
        '3' => $this
          ->t('Three'),
      ],
      '#wrapper_attributes' => ['class' => 'col-md-6 col-xs-12']
    ];
    $form['message'] = [
      '#type' => 'textarea',
      '#title' => $this->t('message'),
      '#required' => true,
      '#default_value' => ' ',
      '#wrapper_attributes' => ['class' => 'col-md-6 col-xs-12']
    ];
    $form['submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('save'),
      '#buttom_type' => 'primary'
    ];
    return $form;
  }

  public function validateForm(array &$form, FormStateInterface $form_state)
  {
//    parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    if (is_numeric($form_state->getValue('first_name'))) {
      $form_state->setErrorByName('first_name', $this->t('Error, The First Name Must Be A String'));
    }
  }

  public function submitForm(array &$form, FormStateInterface $form_state)
  {
//     TODO: Implement submitForm() method.
////    $this->messenger()->addStatus
//    drupal_set_message($this->t('Your first name is @first_name <br>
//              Your last name is @last_name <br>
//              Your email is @email <br>
//              Your phone is @phone<br>
//              Your select is @select<br>
//              Your message is @message <br>',
//      array(
//        '@first_name' => $form_state->getValue('first_name'),
//        '@last_name' => $form_state->getValue('last_name'),
//        '@email' => $form_state->getValue('email'),
//        '@phone' => $form_state->getValue('phone'),
//        '@select' => $form_state->getValue('select'),
//        '@message' => $form_state->getValue('message')
//      )));
//     $picture=$form_state->getValue('picture');
//     $file=File::load($picture[0]);

    $profile_value= array(
      'first_name' => $form_state->getValue('first_name'),
      'last_name' => $form_state->getValue('last_name'),
      'email' => $form_state->getValue('email'),
      'phone' => $form_state->getValue('phone'),
      'select' => $form_state->getValue('select'),
      'message' => $form_state->getValue('message'),
//      'picture'=> $form_state->getValue('picture'),
//      'fid'=>$picture[0],
//      'fid' => $form_state->getValue('picture[0]'),
      );

//    $file->setPermanent();
//    $file->save();
//
    $query=\Drupal::database();
    $query->insert('form_1')->fields( $profile_value)->execute();

    if(!is_null($query)){
      drupal_set_message("DATA SAVED");
      drupal_set_message($this->t('Your first name is @first_name <br>
              Your last name is @last_name <br>
              Your email is @email <br>
              Your phone is @phone<br>
              Your select is @select<br>
              Your message is @message <br>
              Your picture  is @picture <br>'),
        array(
          '@first_name' => $form_state->getValue('first_name'),
          '@last_name' => $form_state->getValue('last_name'),
          '@email' => $form_state->getValue('email'),
          '@phone' => $form_state->getValue('phone'),
          '@select' => $form_state->getValue('select'),
          '@message' => $form_state->getValue('message'),
//          '@picture' => $form_state->getValue('picture'),
        ));

    }
  }
}

